Fine tuning api
GRAAL-Research/deepparse pull request #66
Opened 2020-12-22 23:25 UTC by davebulaval

Implementation of an API for finetuning model on train data and for testing the model on test data.
Also add dataset container for simplicity.
Also add metrics for simplicity.

#55

2020-12-23 22:24 UTC, MAYAS3 requested changes

2020-12-23 23:27 UTC, davebulaval commented on tests/metrics/test_accuracy.py
> +            device=self.a_device)
No since the two are different between the two tests.

2020-12-23 23:27 UTC, davebulaval commented on tests/metrics/test_nll_loss.py
> +        self.an_accuracy_score = torch.tensor(37.2189, device=self.a_device)
ctrl+c error

2020-12-23 23:28 UTC, davebulaval commented on tests/metrics/test_nll_loss.py
> +        self.an_accuracy_score = torch.tensor(37.2189, device=self.a_device)
b0071e8

2020-12-23 23:29 UTC, davebulaval commented on tests/metrics/test_nll_loss.py
> +            device=self.a_device)
The same argument that the setup is different between the two tests.

2020-12-23 23:32 UTC, davebulaval commented on tests/parser/test_address_parser_retrain_api.py
> +        self.data = (torch.rand(batch_size, 1), torch.rand(batch_size, 1))
I changed the name since mock was clearly not the idea here.

2020-12-23 23:32 UTC, davebulaval commented on tests/parser/test_address_parser_retrain_api.py
> +        self.data = (torch.rand(batch_size, 1), torch.rand(batch_size, 1))
3dfd34b

2020-12-23 23:34 UTC, davebulaval commented on tests/network/integration/test_integration_seq2seq_model.py
> +        random_mock.assert_not_called()
The problem is mostly to transfer all the data we use for the tests (decoder_input, max_length, ...).

2020-12-23 23:36 UTC, davebulaval commented on deepparse/converter/data_padding.py
> +    padded_target_vectors = pad_sequence(target_vectors, batch_first=True)
Good catch

2020-12-23 23:50 UTC, davebulaval commented on deepparse/converter/data_padding.py
> +    padded_target_vectors = pad_sequence(target_vectors, batch_first=True)
7c813f8

2020-12-23 23:52 UTC, davebulaval commented on tests/network/integration/base.py
> +            file = open(f"./network/integration/to_predict_{model_type}.p", "rb")
Didn't know about that difference.

2020-12-23 23:53 UTC, davebulaval commented on tests/dataset_container/test_dataset_container.py
> +        self.assertListOfArraysEqual(expected, actual)
I test both, ADatasetContainer which is an implementation of the interface and Pickle, maybe we should split them for clarity?

2020-12-24 01:31 UTC, MAYAS3 commented on tests/dataset_container/test_dataset_container.py
> +        self.assertListOfArraysEqual(expected, actual)
What I actually meant is testing Pickle alone, no need to test ADatasetContainer

2020-12-24 01:37 UTC, davebulaval commented on tests/dataset_container/test_dataset_container.py
> +        self.assertListOfArraysEqual(expected, actual)
Allright, I agree

2020-12-24 01:39 UTC, davebulaval commented on tests/dataset_container/test_dataset_container.py
> +        self.assertListOfArraysEqual(expected, actual)
Removed.

2020-12-24 02:17 UTC, MAYAS3 requested changes

2020-12-24 02:17 UTC, MAYAS3 commented on tests/network/integration/test_integration_decoder.py
> +    def encoder_input_setUp(self):
```suggestion
    def decoder_input_setUp(self):
```

2020-12-24 02:17 UTC, MAYAS3 commented on tests/network/integration/test_integration_decoder.py
> +        self.encoder_input_setUp()
```suggestion
        self.decoder_input_setUp()
```

2020-12-24 02:17 UTC, MAYAS3 commented on tests/network/integration/test_integration_decoder.py
> +    def encoder_input_setUp(self):
Right?

2020-12-24 19:32 UTC, MAYAS3 requested changes

2020-12-24 19:32 UTC, MAYAS3 commented on tests/network/integration/test_integration_decoder.py
> +        file = open("./decoder_hidden.p", "rb")
```suggestion
        file = open("./tests/network/integration/decoder_hidden.p", "rb")
```

2020-12-24 20:40 UTC, merged