[feature] Tags
GRAAL-Research/deepparse pull request #81
Opened 2021-03-30 00:49 UTC by davebulaval

Add a feature to modify the list of tags during training and use the same list during inference later on.

Also fixed some integration tests due to changes in Poutyne.

2021-04-05 19:58 UTC, davebulaval commented
The feature allows a user to retrain a model with its own tags and also allows a user (with minimal manipulation as possible) to test the pre-trained model with its own tags (without retraining).

2021-04-05 20:30 UTC, davebulaval commented
Possible improvements of this beta approach:

- Use a retrain_param_dict with possible keys: freeze_encoder, freeze_decoder and prediction_tags_dict.

2021-04-24 22:45 UTC, davebulaval commented
Add test in `test_integration_address_parser_retrain_new_address_components`

2021-06-02 19:56 UTC, MAYAS3 commented on deepparse/parser/address_parser.py
> +            self._model_factory(verbose=False, prediction_layer_len=self.tags_converter.dim)
- Lorsque le model est recréé avec *_model_factory* ici ça repart des modèles bpemb et fasttext même si le user a instancié la classe avec un *pre_trained_path* alors que si *prediction_tags* n'est pas spécifié le réentrainement est fait avec le modèle contenu dans *pre_trained_path*
- Aussi, pourquoi recréer le modèle et non pas juste modifier directement la couche de classification ?

2021-06-02 20:09 UTC, davebulaval commented on deepparse/parser/address_parser.py
> +            exp.load_checkpoint(model_path)
Je ne suis pas certain de comprendre.

2021-06-02 20:10 UTC, davebulaval commented on deepparse/parser/address_parser.py
> +            self._model_factory(verbose=False, prediction_layer_len=self.tags_converter.dim)
Bon point.

2021-06-02 20:54 UTC, MAYAS3 commented on deepparse/parser/address_parser.py
> +            exp.load_checkpoint(model_path)
Mettons j'initialise la classe avec *bpemb* dans le constructeur, je peux quand même spécifier *"fasttext"* ici et je serais en train de tester avec le modèle fasttext un parser initialisé avec *bpemb*

2021-06-07 15:03 UTC, davebulaval commented on deepparse/parser/address_parser.py
> +            exp.load_checkpoint(model_path)
I've made some change.

2021-06-07 15:04 UTC, davebulaval commented on deepparse/parser/address_parser.py
> +                    address_parser.test(test_container, checkpoint="fasttext") # test with fasttext model
removed

2021-06-09 18:46 UTC, MAYAS3 requested changes

2021-06-09 18:46 UTC, MAYAS3 commented on deepparse/network/seq2seq.py
> +    Abstract class for Seq2Seq network. By default, the network use the config as design in our article for the encoder
```suggestion
    Abstract class for Seq2Seq network. By default, the network uses the config as designed in our article for the encoder
```

2021-06-09 18:46 UTC, MAYAS3 commented on deepparse/network/seq2seq.py
> +    When retraining with a different tag dictionary the output_size is change to the size of that dictionary.
```suggestion
    When retraining with a different tag dictionary the output_size is changed to the size of that dictionary.
```

2021-06-09 18:46 UTC, MAYAS3 commented on deepparse/network/seq2seq.py
> +        Verify if the output dimension are similar as ``size``.
```suggestion
        Verify if the output dimension is similar to ``size``.
```

2021-06-09 18:46 UTC, MAYAS3 commented on deepparse/parser/address_parser.py
> +    networks either with fastText or BPEmb. The default predictions tags are the following
```suggestion
    networks either with fastText or BPEmb. The default prediction tags are the following
```

2021-06-09 18:46 UTC, MAYAS3 commented on deepparse/parser/address_parser.py
> +                pre-trained  model prediction tags.
```suggestion
            prediction_tags (Union[dict, None]): A dictionary where the keys are the address components
                (e.g. street name) and the values are the components indices (from 0 to N + 1) to use during retraining
                of a model. The ``+ 1`` corresponds to the End Of Sequence (EOS) token that needs to be included in the dictionary.
                We will use the length of this dictionary for the output size of the prediction layer. We also save
                the dictionary to be used later on when you load the model. Default is None, meaning we use our
                pre-trained model prediction tags.
```

2021-06-09 18:46 UTC, MAYAS3 commented on deepparse/parser/address_parser.py
> +        retrained with different prediction tags, we will use those tags.
```suggestion
        Method to test a retrained or a pre-trained model using a dataset with the default tags. If you test a
        retrained model with different prediction tags, we will use those tags.
```

2021-06-09 18:46 UTC, MAYAS3 commented on deepparse/parser/formated_parsed_address.py
> +        are the value of those components. For example, the parsed address ``<StreetNumber> 305 <StreetName>
```suggestion
        Method to convert a parsed address into a dictionary where the keys are the address components and the values
        are the value of those components. For example, the parsed address ``<StreetNumber> 305 <StreetName>
```

2021-06-09 18:46 UTC, MAYAS3 commented on deepparse/parser/formated_parsed_address.py
> +            A dictionary where the keys are the selected (or default) fields and the value are the corresponding value
```suggestion
            A dictionary where the keys are the selected (or default) fields and the values are the corresponding value
```

2021-06-09 19:09 UTC, MAYAS3 approved these changes

2021-06-09 19:11 UTC, merged